version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    tty: true
    command: 'yarn dev'

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./backend:/backend
    tty: true
    command: 'yarn dev'
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./db/db:/data/db
      - ./db/configdb:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongo
